
    package sas;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Types;
import java.io.ByteArrayOutputStream;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.ByteArrayInputStream;
import java.text.ParseException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
/**
 *
 * @author Rayogitra
 */
class DatabaseConnection {
    private static final String URL = "jdbc:mysql://localhost:3306/finals_db";
    private static final String USER = "root";
    private static final String PASSWORD = "";
    
    public static Connection getConnection() throws SQLException {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            return DriverManager.getConnection(URL, USER, PASSWORD);
        } catch (ClassNotFoundException e) {
            throw new SQLException("MySQL JDBC Driver not found", e);
        }
    }
}

public class user_sign_in_1 extends javax.swing.JFrame {

    private Connection connection;
private PreparedStatement pstmt;
private final String DB_URL = "jdbc:mysql://localhost:3306/finals_db";
private final String DB_USER = "root";
private final String DB_PASS = "";
    private Webcam webcam = null;
    private WebcamPanel webcamPanel = null;
    private BufferedImage capturedImage = null;
    public user_sign_in_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        Campus = new javax.swing.JLabel();
        Program = new javax.swing.JLabel();
        classification = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        birthplace = new javax.swing.JLabel();
        province = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        townorcity = new javax.swing.JLabel();
        barangay = new javax.swing.JLabel();
        district = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        txtmname = new java.awt.TextField();
        txtfname = new java.awt.TextField();
        txtBirthPlace = new java.awt.TextField();
        txtlname = new java.awt.TextField();
        txtAddress = new java.awt.TextField();
        cProvince = new javax.swing.JComboBox<>();
        cCity = new javax.swing.JComboBox<>();
        txtBarangay = new java.awt.TextField();
        txtEmail = new java.awt.TextField();
        sexatbirth = new javax.swing.JLabel();
        scheme = new javax.swing.JLabel();
        btnScheme1 = new javax.swing.JRadioButton();
        btnScheme2 = new javax.swing.JRadioButton();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        civilstatus = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtZip = new java.awt.TextField();
        nationality = new javax.swing.JLabel();
        reion = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        height = new javax.swing.JLabel();
        weightname = new javax.swing.JLabel();
        txtReligion = new java.awt.TextField();
        txtNationality = new java.awt.TextField();
        txtContact = new java.awt.TextField();
        txtMobileNo = new java.awt.TextField();
        txtHeight = new java.awt.TextField();
        txtWeight = new java.awt.TextField();
        jPanel7 = new javax.swing.JPanel();
        photoPreview = new javax.swing.JLabel();
        cCampus = new javax.swing.JComboBox<>();
        cCourse = new javax.swing.JComboBox<>();
        cYearLevel = new javax.swing.JComboBox<>();
        btnTakePhoto = new javax.swing.JButton();
        btnUploadPhoto = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cSection = new javax.swing.JComboBox<>();
        cDistrict = new javax.swing.JComboBox<>();
        cCivilStatus = new javax.swing.JComboBox<>();
        cDayDate = new javax.swing.JComboBox<>();
        cMonthDate = new javax.swing.JComboBox<>();
        cYearDate = new javax.swing.JComboBox<>();
        email1 = new javax.swing.JLabel();
        txtPassword = new java.awt.TextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 145, 77));
        jPanel2.setForeground(new java.awt.Color(255, 145, 77));

        Title.setBackground(new java.awt.Color(0, 0, 0));
        Title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Title.setText("STUDENT SIGN UP PANEL");

        jPanel3.setBackground(new java.awt.Color(214, 237, 198));

        jPanel4.setBackground(new java.awt.Color(234, 245, 226));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Personal information");

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        Campus.setBackground(new java.awt.Color(0, 0, 0));
        Campus.setText("Campus");

        Program.setBackground(new java.awt.Color(0, 0, 0));
        Program.setText("Program");

        classification.setBackground(new java.awt.Color(0, 0, 0));
        classification.setText("Year Level");

        jPanel5.setForeground(new java.awt.Color(153, 153, 153));

        header.setBackground(new java.awt.Color(0, 0, 0));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setText("Personal Background");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header)
                .addContainerGap(1159, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header)
        );

        Name.setBackground(new java.awt.Color(0, 0, 0));
        Name.setText("Name");

        birthplace.setBackground(new java.awt.Color(0, 0, 0));
        birthplace.setText("Place of Birth");

        province.setBackground(new java.awt.Color(0, 0, 0));
        province.setText("Province");

        address.setBackground(new java.awt.Color(0, 0, 0));
        address.setText("Home Address");

        townorcity.setBackground(new java.awt.Color(0, 0, 0));
        townorcity.setText("Town/City");

        barangay.setBackground(new java.awt.Color(0, 0, 0));
        barangay.setText("Barangay");

        district.setBackground(new java.awt.Color(0, 0, 0));
        district.setText("District");

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setText("E-mail");

        txtmname.setText("Middle Name");
        txtmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmnameActionPerformed(evt);
            }
        });

        txtfname.setText("First Name");
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });

        txtBirthPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthPlaceActionPerformed(evt);
            }
        });

        txtlname.setText("Last Name");
        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        cProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NCR", "CALABARZON", "BULACAN", "OTHERS" }));
        cProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cProvinceActionPerformed(evt);
            }
        });

        cCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caloocan City", "Quezon City", "Valenzuela City", "Malabon City", "Navotas City", "Manila City", "Others" }));

        txtBarangay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarangayActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        sexatbirth.setBackground(new java.awt.Color(0, 0, 0));
        sexatbirth.setText("Sex At Birth");

        scheme.setBackground(new java.awt.Color(0, 0, 0));
        scheme.setText("Scheme");

        buttonGroup1.add(btnScheme1);
        btnScheme1.setText("Scheme 1");

        buttonGroup1.add(btnScheme2);
        btnScheme2.setText("Scheme 2");

        buttonGroup2.add(btnMale);
        btnMale.setText("Male");

        buttonGroup2.add(btnFemale);
        btnFemale.setText("Female");

        civilstatus.setBackground(new java.awt.Color(0, 0, 0));
        civilstatus.setText("Civil Status");

        birthday.setBackground(new java.awt.Color(0, 0, 0));
        birthday.setText("Date of Birth");

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("ZIP Code");

        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });

        nationality.setBackground(new java.awt.Color(0, 0, 0));
        nationality.setText("Nationality");

        reion.setBackground(new java.awt.Color(0, 0, 0));
        reion.setText("Religion");

        contact.setBackground(new java.awt.Color(0, 0, 0));
        contact.setText("Contact no.");

        mobile.setBackground(new java.awt.Color(0, 0, 0));
        mobile.setText("Mobile no.");

        height.setBackground(new java.awt.Color(0, 0, 0));
        height.setText("Height(in cm)");

        weightname.setBackground(new java.awt.Color(0, 0, 0));
        weightname.setText("Weight(in kg)");

        txtReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReligionActionPerformed(evt);
            }
        });

        txtNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalityActionPerformed(evt);
            }
        });

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        txtMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileNoActionPerformed(evt);
            }
        });

        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        photoPreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photoPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photoPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        cCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Congress", "Camarin", "South" }));
        cCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCampusActionPerformed(evt);
            }
        });

        cCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSEMC", "BSIT", "BSIS", "BSCS" }));

        cYearLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        btnTakePhoto.setText("Take Camera");
        btnTakePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakePhotoActionPerformed(evt);
            }
        });

        btnUploadPhoto.setText("Upload Photo");
        btnUploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPhotoActionPerformed(evt);
            }
        });

        btnSubmit.setText("Confirm Submission");
        btnSubmit.setToolTipText("");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setText("Section");

        cSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        cSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSectionActionPerformed(evt);
            }
        });

        cDistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        cCivilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Widowed", "Divorced", "Separated", "Civil Partnership" }));
        cCivilStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCivilStatusActionPerformed(evt);
            }
        });

        cDayDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cDayDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDayDateActionPerformed(evt);
            }
        });

        cMonthDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cMonthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMonthDateActionPerformed(evt);
            }
        });

        cYearDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        cYearDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cYearDateActionPerformed(evt);
            }
        });

        email1.setBackground(new java.awt.Color(0, 0, 0));
        email1.setText("Password");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(Name)
                                    .addGap(89, 89, 89)
                                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addComponent(province)
                                            .addGap(75, 75, 75))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(address)
                                                .addComponent(townorcity))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(birthplace)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtBirthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(email)
                                                    .addComponent(barangay))
                                                .addGap(72, 72, 72))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                .addComponent(scheme)
                                                .addGap(79, 79, 79)))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(district)
                                            .addGap(84, 84, 84)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(email1)
                                        .addGap(72, 72, 72)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(btnScheme1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnScheme2))
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBarangay, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(sexatbirth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFemale))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel37)
                                                .addComponent(nationality)
                                                .addComponent(reion)
                                                .addComponent(contact)
                                                .addComponent(mobile)
                                                .addComponent(height)
                                                .addComponent(weightname))
                                            .addGap(16, 16, 16))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addComponent(birthday)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(civilstatus)
                                        .addGap(22, 22, 22)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(cDayDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cMonthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cYearDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classification)
                            .addComponent(Campus)
                            .addComponent(Program))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cSection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cYearLevel, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cCampus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 849, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTakePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUploadPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnUploadPhoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTakePhoto))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Campus)
                            .addComponent(cCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Program)
                            .addComponent(cCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classification)
                            .addComponent(cYearLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name)
                            .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthplace)
                            .addComponent(txtBirthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(province)
                            .addComponent(reion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(townorcity)
                            .addComponent(cCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nationality))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scheme)
                            .addComponent(btnScheme1)
                            .addComponent(btnScheme2))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mobile)
                                            .addComponent(txtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(contact))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(height)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(weightname)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(barangay)
                                    .addComponent(txtBarangay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(district)
                                    .addComponent(cDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email1)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexatbirth)
                            .addComponent(btnMale)
                            .addComponent(btnFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(civilstatus)
                            .addComponent(cCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birthday)
                            .addComponent(cYearDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cMonthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cDayDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addComponent(btnSubmit)
                .addGap(30, 30, 30))
        );

        jScrollPane4.setViewportView(jPanel6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(574, 574, 574)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 592, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1347, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sas/Logoutresized.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(538, 538, 538)
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Title)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnameActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtBirthPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthPlaceActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtBarangayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarangayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarangayActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipActionPerformed

    private void txtReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReligionActionPerformed

    private void txtNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalityActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNoActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnUploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPhotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Image Files", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fileChooser.getSelectedFile();
                capturedImage = ImageIO.read(file);

                // Display in the preview label
                if (capturedImage != null) {
                    ImageIcon icon = new ImageIcon(capturedImage);
                    Image scaledImage = icon.getImage().getScaledInstance(
                        photoPreview.getWidth(),
                        photoPreview.getHeight(),
                        Image.SCALE_SMOOTH);
                    photoPreview.setIcon(new ImageIcon(scaledImage));
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                    "Error loading image: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUploadPhotoActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (validateFields()) {
            try {
                saveStudentData();
                JOptionPane.showMessageDialog(this, "Student information saved successfully!",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                clearFields();
            } catch (SQLException | ParseException ex) {
                JOptionPane.showMessageDialog(this, "Error saving data: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }

        private boolean validateFields() {
            // Basic validation - you can expand this
            if (txtfname.getText().isEmpty() || txtlname.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "First name and last name are required!",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
                return false;
            }

            if (photoPreview.getIcon() == null) {
                JOptionPane.showMessageDialog(this, "Please take or upload a photo!",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
                return false;
            }

            return true;
        }

        private void saveStudentData() throws SQLException, ParseException {
// Main students table insert (excluding attendance)
String mainTableSql = "INSERT INTO students (school_year, section, grade, photo, campus, " +
        "birth_place, home_address, province, city, scheme, barangay, district, sex, " +
        "civil_status, birth_date, zip_code, nationality, religion, contact_no, mobile_no, " +
        "height, weight, email, password, last_name, first_name, middle_name) " +
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

// Program-specific tables (same approach)
String programTableSql = "";
String course = cCourse.getSelectedItem().toString();

switch(course) {
    case "BSIS":
        programTableSql = "INSERT INTO bsis_students (school_year, section, grade, photo, campus, " +
                "birth_place, home_address, province, city, scheme, barangay, district, sex, " +
                "civil_status, birth_date, zip_code, nationality, religion, contact_no, mobile_no, " +
                "height, weight, email, password, last_name, first_name, middle_name) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        break;
    case "BSIT":
        programTableSql = "INSERT INTO bsit_students (school_year, section, grade, photo, campus, " +
                "birth_place, home_address, province, city, scheme, barangay, district, sex, " +
                "civil_status, birth_date, zip_code, nationality, religion, contact_no, mobile_no, " +
                "height, weight, email, password, last_name, first_name, middle_name) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        break;
    case "BSCS":
        programTableSql = "INSERT INTO bscs_students (school_year, section, grade, photo, campus, " +
                "birth_place, home_address, province, city, scheme, barangay, district, sex, " +
                "civil_status, birth_date, zip_code, nationality, religion, contact_no, mobile_no, " +
                "height, weight, email, password, last_name, first_name, middle_name) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        break;
}
    
   try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement mainPstmt = conn.prepareStatement(mainTableSql);
         PreparedStatement programPstmt = programTableSql.isEmpty() ? null : conn.prepareStatement(programTableSql)) {

        // Set parameters for main table
        setCommonParameters(mainPstmt);
        
        // Execute main table insert
        mainPstmt.executeUpdate();
        
        // If a program-specific table was selected, insert there too
        if (programPstmt != null) {
            setCommonParameters(programPstmt);
            programPstmt.executeUpdate();
        }
    }
}
 // Updated helper method without attendance
private void setCommonParameters(PreparedStatement pstmt) throws SQLException {
    String birthDate = cYearDate.getSelectedItem() + "-" +
            cMonthDate.getSelectedItem() + "-" +
            cDayDate.getSelectedItem();
    
    int paramIndex = 1;
    
    // School year
    pstmt.setString(paramIndex++, "2023-2024");
    
    // Section
    pstmt.setString(paramIndex++, cSection.getSelectedItem().toString());
    
    // Grade (assuming empty/null for new students)
    pstmt.setNull(paramIndex++, Types.VARCHAR);
    
    // Photo
    if (capturedImage != null) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            ImageIO.write(capturedImage, "jpg", baos);
            pstmt.setBytes(paramIndex++, baos.toByteArray());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error processing image", "Error", JOptionPane.ERROR_MESSAGE);
            pstmt.setNull(paramIndex++, Types.BLOB);
        }
    } else {
        pstmt.setNull(paramIndex++, Types.BLOB);
    }
    
    // Campus
    pstmt.setString(paramIndex++, cCampus.getSelectedItem().toString());
    
    // Birth place
    pstmt.setString(paramIndex++, txtBirthPlace.getText());
    
    // Home address
    pstmt.setString(paramIndex++, txtAddress.getText());
    
    // Province
    pstmt.setString(paramIndex++, cProvince.getSelectedItem().toString());
    
    // City
    pstmt.setString(paramIndex++, cCity.getSelectedItem().toString());
    
    // Scheme
    pstmt.setString(paramIndex++, btnScheme1.isSelected() ? "Scheme 1" : "Scheme 2");
    
    // Barangay
    pstmt.setString(paramIndex++, txtBarangay.getText());
    
    // District
    pstmt.setString(paramIndex++, cDistrict.getSelectedItem().toString());
    
    // Sex
    pstmt.setString(paramIndex++, btnMale.isSelected() ? "Male" : "Female");
    
    // Civil status
    pstmt.setString(paramIndex++, cCivilStatus.getSelectedItem().toString());
    
    // Birth date
    pstmt.setDate(paramIndex++, java.sql.Date.valueOf(birthDate));
    
    // ZIP code
    pstmt.setString(paramIndex++, txtZip.getText());
    
    // Nationality
    pstmt.setString(paramIndex++, txtNationality.getText());
    
    // Religion
    pstmt.setString(paramIndex++, txtReligion.getText());
    
    // Contact no
    pstmt.setString(paramIndex++, txtContact.getText());
    
    // Mobile no
    pstmt.setString(paramIndex++, txtMobileNo.getText());
    
    // Height
    pstmt.setString(paramIndex++, txtHeight.getText());
    
    // Weight
    pstmt.setString(paramIndex++, txtWeight.getText());
    
    // Email
    pstmt.setString(paramIndex++, txtEmail.getText());
    
    // Password
    pstmt.setString(paramIndex++, txtPassword.getText());
    
    // Last name
    pstmt.setString(paramIndex++, txtlname.getText());
    
    // First name
    pstmt.setString(paramIndex++, txtfname.getText());
    
    // Middle name
    pstmt.setString(paramIndex++, txtmname.getText());
}
        private void clearFields() {
            // Clear all input fields
            txtfname.setText("");
            txtmname.setText("");
            txtlname.setText("");
            txtBirthPlace.setText("");
            txtAddress.setText("");
            txtBarangay.setText("");
            txtEmail.setText("");
            txtPassword.setText("");
            txtZip.setText("");
            txtNationality.setText("");
            txtReligion.setText("");
            txtContact.setText("");
            txtMobileNo.setText("");
            txtHeight.setText("");
            txtWeight.setText("");

            // Reset combo boxes and radio buttons
            cCampus.setSelectedIndex(0);
            cCourse.setSelectedIndex(0);
            cYearLevel.setSelectedIndex(0);
            cSection.setSelectedIndex(0);
            cProvince.setSelectedIndex(0);
            cCity.setSelectedIndex(0);
            cDistrict.setSelectedIndex(0);
            cCivilStatus.setSelectedIndex(0);
            cDayDate.setSelectedIndex(0);
            cMonthDate.setSelectedIndex(0);
            cYearDate.setSelectedIndex(0);
            buttonGroup1.clearSelection();
            buttonGroup2.clearSelection();

            // Clear photo
            photoPreview.setIcon(null);
            capturedImage = null;
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCampusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCampusActionPerformed

    private void cSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSectionActionPerformed

    private void cProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cProvinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cProvinceActionPerformed

    private void cCivilStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCivilStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCivilStatusActionPerformed

    private void cDayDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDayDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDayDateActionPerformed

    private void cMonthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMonthDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cMonthDateActionPerformed

    private void cYearDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cYearDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cYearDateActionPerformed

    private void btnTakePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakePhotoActionPerformed
        try {
            // Get default webcam
            webcam = Webcam.getDefault();

            if (webcam != null) {
                // Set HD resolution
                webcam.setViewSize(WebcamResolution.VGA.getSize());

                // Create webcam panel
                webcamPanel = new WebcamPanel(webcam);
                webcamPanel.setFPSDisplayed(true);
                webcamPanel.setDisplayDebugInfo(true);
                webcamPanel.setImageSizeDisplayed(true);
                webcamPanel.setMirrored(true);

                // Create a dialog to show the webcam feed
                JDialog dialog = new JDialog(this, "Take Photo", true);
                dialog.setLayout(new BorderLayout());
                dialog.add(webcamPanel, BorderLayout.CENTER);

                // Add capture button
                JButton captureButton = new JButton("Capture");
                captureButton.addActionListener(e -> {
                    // Capture image
                    capturedImage = webcam.getImage();

                    // Display in the preview label
                    if (capturedImage != null) {
                        ImageIcon icon = new ImageIcon(capturedImage);
                        Image scaledImage = icon.getImage().getScaledInstance(
                            photoPreview.getWidth(),
                            photoPreview.getHeight(),
                            Image.SCALE_SMOOTH);
                        photoPreview.setIcon(new ImageIcon(scaledImage));
                    }

                    // Close the dialog
                    dialog.dispose();
                });

                JPanel buttonPanel = new JPanel();
                buttonPanel.add(captureButton);
                dialog.add(buttonPanel, BorderLayout.SOUTH);

                // Set dialog properties
                dialog.pack();
                dialog.setLocationRelativeTo(this);
                dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialog.setVisible(true);

                // Clean up when dialog closes
                dialog.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent e) {
                        if (webcam != null) {
                            webcam.close();
                            webcam = null;
                        }
                        webcamPanel = null;
                    }
                });
            } else {
                JOptionPane.showMessageDialog(this,
                    "No webcam detected",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error accessing webcam: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            if (webcam != null) {
                webcam.close();
                webcam = null;
            }
            webcamPanel = null;
        }
    }//GEN-LAST:event_btnTakePhotoActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           
        this.dispose();
        new testing_1().setVisible(true); 
              
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_sign_in_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_sign_in_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_sign_in_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_sign_in_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_sign_in_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Campus;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Program;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel address;
    private javax.swing.JLabel barangay;
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel birthplace;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JRadioButton btnScheme1;
    private javax.swing.JRadioButton btnScheme2;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnTakePhoto;
    private javax.swing.JButton btnUploadPhoto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cCampus;
    private javax.swing.JComboBox<String> cCity;
    private javax.swing.JComboBox<String> cCivilStatus;
    private javax.swing.JComboBox<String> cCourse;
    private javax.swing.JComboBox<String> cDayDate;
    private javax.swing.JComboBox<String> cDistrict;
    private javax.swing.JComboBox<String> cMonthDate;
    private javax.swing.JComboBox<String> cProvince;
    private javax.swing.JComboBox<String> cSection;
    private javax.swing.JComboBox<String> cYearDate;
    private javax.swing.JComboBox<String> cYearLevel;
    private javax.swing.JLabel civilstatus;
    private javax.swing.JLabel classification;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel district;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel header;
    private javax.swing.JLabel height;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel nationality;
    private javax.swing.JLabel photoPreview;
    private javax.swing.JLabel province;
    private javax.swing.JLabel reion;
    private javax.swing.JLabel scheme;
    private javax.swing.JLabel sexatbirth;
    private javax.swing.JLabel townorcity;
    private java.awt.TextField txtAddress;
    private java.awt.TextField txtBarangay;
    private java.awt.TextField txtBirthPlace;
    private java.awt.TextField txtContact;
    private java.awt.TextField txtEmail;
    private java.awt.TextField txtHeight;
    private java.awt.TextField txtMobileNo;
    private java.awt.TextField txtNationality;
    private java.awt.TextField txtPassword;
    private java.awt.TextField txtReligion;
    private java.awt.TextField txtWeight;
    private java.awt.TextField txtZip;
    private java.awt.TextField txtfname;
    private java.awt.TextField txtlname;
    private java.awt.TextField txtmname;
    private javax.swing.JLabel weightname;
    // End of variables declaration//GEN-END:variables
}
